export const CHINA_CITY_MAP: Record<string, string> = {
  "Aba Zangzu Qiangzu Zizhizhou": "阿坝藏族羌族自治州",
  "Ankang": "安康市",
  "Anqing": "安庆市",
  "Anqing Shi": "安庆市",
  "Anshan": "鞍山市",
  "Anshun": "安顺市",
  "Anyang": "安阳市",
  "Anyang Shi": "安阳市",
  "Baicheng": "白城市",
  "Baise City": "百色市",
  "Baise Shi": "百色市",
  "Baishan": "白山市",
  "Baiyin": "白银市",
  "Baoding": "保定市",
  "Baoji Shi": "宝鸡市",
  "Baoshan": "保山市",
  "Baotou": "包头市",
  "Bazhong Shi": "巴中市",
  "Beihai": "北海市",
  "Beijing": "北京市",
  "Bengbu": "蚌埠市",
  "Benxi": "本溪市",
  "Bijie": "毕节市",
  "Binzhou": "滨州市",
  "Bozhou": "亳州市",
  "Cangzhou": "沧州市",
  "Cangzhou Shi": "沧州市",
  "ChangZhou": "常州市",
  "Changchun": "长春市",
  "Changde": "常德市",
  "Changji Huizu Zizhizhou": "昌吉回族自治州",
  "Changsha": "长沙市",
  "Changsha Shi": "长沙市",
  "Changzhi": "长治市",
  "Changzhou": "常州市",
  "Chaoyang": "朝阳市",
  "Chaozhou": "潮州市",
  "Chengde": "承德市",
  "Chengde Prefecture": "承德市",
  "Chengdu": "成都市",
  "Chenzhou": "郴州市",
  "Chifeng": "赤峰市",
  "Chizhou": "池州市",
  "Chizhou Shi": "池州市",
  "Chongqing": "重庆市",
  "Chongzuo Shi": "崇左市",
  "Chuxiong Yizu Zizhizhou": "楚雄彝族自治州",
  "Chuzhou": "滁州市",
  "Chuzhou Shi": "滁州市",
  "Dali Baizu Zizhizhou": "大理白族自治州",
  "Dalian": "大连市",
  "Dandong": "丹东市",
  "Daqing": "大庆市",
  "Datong": "大同市",
  "Datong Shi": "大同市",
  "Dazhou": "达州市",
  "Dehong Daizu Jingpozu Zizhizhou": "德宏傣族景颇族自治州",
  "Deyang": "德阳市",
  "Dezhou": "德州市",
  "Dingxi Shi": "定西市",
  "Dongguan": "东莞市",
  "Enshi Tujiazu Miaozu Zizhizhou": "恩施土家族苗族自治州",
  "Ezhou": "鄂州市",
  "Ezhou Shi": "鄂州市",
  "Fangchenggang Shi": "防城港市",
  "Foshan": "佛山市",
  "Foshan Shi": "佛山市",
  "Fushun": "抚顺市",
  "Fuxin": "阜新市",
  "Fuyang": "阜阳市",
  "Fuyang Shi": "阜阳市",
  "Fuzhou": "抚州市",
  "Ganzhou": "赣州市",
  "Ganzhou Shi": "赣州市",
  "Guangyuan": "广元市",
  "Guangzhou": "广州市",
  "Guangzhou Shi": "广州市",
  "Guigang": "贵港市",
  "Guilin": "桂林市",
  "Guilin Shi": "桂林市",
  "Guiyang": "贵阳市",
  "Haikou": "海口市",
  "Hami": "哈密市",
  "Handan": "邯郸市",
  "Hangzhou": "杭州市",
  "Hanzhong": "汉中市",
  "Hebi": "鹤壁市",
  "Hechi Shi": "河池市",
  "Hefei": "合肥市",
  "Hefei Shi": "合肥市",
  "Hegang": "鹤岗市",
  "Heihe": "黑河市",
  "Hengshui": "衡水市",
  "Hengyang": "衡阳市",
  "Heyuan": "河源市",
  "Heze": "菏泽市",
  "Honghe Hanizu Yizu Zizhizhou": "红河哈尼族彝族自治州",
  "HuaiAn": "淮安市",
  "Huaibei": "淮北市",
  "Huaihua": "怀化市",
  "Huainan": "淮南市",
  "Huainan Shi": "淮南市",
  "Huanggang": "黄冈市",
  "Huangnan Zangzu Zizhizhou": "黄南藏族自治州",
  "Huangshan": "黄山市",
  "Huangshan Shi": "黄山市",
  "Huangshi": "黄石市",
  "Huizhou": "惠州市",
  "Huludao": "葫芦岛市",
  "Huludao Shi": "葫芦岛市",
  "Huzhou": "湖州市",
  "Jiamusi": "佳木斯市",
  "Jiangmen": "江门市",
  "Jiaozuo": "焦作市",
  "Jiaxing": "嘉兴市",
  "Jiaxing Shi": "嘉兴市",
  "Jiayuguan": "嘉峪关市",
  "Jieyang": "揭阳市",
  "Jilin": "吉林市",
  "Jinan": "济南市",
  "Jinchang": "金昌市",
  "Jincheng": "晋城市",
  "Jingdezhen": "景德镇市",
  "Jingdezhen Shi": "景德镇市",
  "Jingmen": "荆门市",
  "Jingmen Shi": "荆门市",
  "Jingzhou": "荆州市",
  "Jinhua": "金华市",
  "Jining": "济宁市",
  "Jinzhong Shi": "晋中市",
  "Jinzhou": "锦州市",
  "Jiujiang": "九江市",
  "Jiuquan": "酒泉市",
  "Jixi": "鸡西市",
  "Jiyuan": "济源市",
  "Kaifeng": "开封市",
  "Kunming": "昆明市",
  "Laibin": "来宾市",
  "Langfang": "廊坊市",
  "Langfang Shi": "廊坊市",
  "Lanzhou": "兰州市",
  "Leshan": "乐山市",
  "LianYunGang": "连云港市",
  "Liangshan Yizu Zizhizhou": "凉山彝族自治州",
  "Lianyungang Shi": "连云港市",
  "Liaocheng": "聊城市",
  "Liaoyang": "辽阳市",
  "Liaoyuan": "辽源市",
  "Lijiang": "丽江市",
  "Lincang Shi": "临沧市",
  "Linfen": "临汾市",
  "Linxia Huizu Zizhizhou": "临夏回族自治州",
  "Linyi": "临沂市",
  "Lishui": "丽水市",
  "Liupanshui": "六盘水市",
  "Liuzhou Shi": "柳州市",
  "Longnan Shi": "陇南市",
  "Longyan": "龙岩市",
  "Loudi": "娄底市",
  "Luohe": "漯河市",
  "Luohe Shi": "漯河市",
  "Luoyang": "洛阳市",
  "Luzhou": "泸州市",
  "Lüliang": "吕梁市",
  "Maoming": "茂名市",
  "Meishan Shi": "眉山市",
  "Meizhou": "梅州市",
  "Mianyang": "绵阳市",
  "Mudanjiang": "牡丹江市",
  "NanJing": "南京市",
  "NanTong": "南通市",
  "Nanchang": "南昌市",
  "Nanchong": "南充市",
  "Nanjing": "南京市",
  "Nanning": "南宁市",
  "Nanping": "南平市",
  "Nantong": "南通市",
  "Nanyang": "南阳市",
  "Neijiang": "内江市",
  "Ningbo": "宁波市",
  "Ningde": "宁德市",
  "Nujiang Lisuzu Zizhizhou": "怒江傈僳族自治州",
  "Panjin Shi": "盘锦市",
  "Panzhihua": "攀枝花市",
  "Pingdingshan": "平顶山市",
  "Pingliang": "平凉市",
  "Pingxiang": "萍乡市",
  "Putian": "莆田市",
  "Puyang": "濮阳市",
  "Puyang Shi": "濮阳市",
  "Qianjiang": "潜江市",
  "Qingdao": "青岛市",
  "Qingyang": "庆阳市",
  "Qingyang Shi": "庆阳市",
  "Qingyuan": "清远市",
  "Qinhuangdao": "秦皇岛市",
  "Qinzhou": "钦州市",
  "Qionghai": "琼海市",
  "Quanzhou": "泉州市",
  "Qujing": "曲靖市",
  "Quzhou": "衢州市",
  "Rikaze": "日喀则市",
  "Rizhao": "日照市",
  "Sanming": "三明市",
  "Sansha": "三沙市",
  "Sanya": "三亚市",
  "Shanghai": "上海市",
  "Shangqiu": "商丘市",
  "Shangrao": "上饶市",
  "Shannan Diqu": "山南市",
  "Shantou": "汕头市",
  "Shanwei": "汕尾市",
  "Shaoguan": "韶关市",
  "Shaoxing": "绍兴市",
  "Shennongjia": "神农架林区",
  "Shenyang": "沈阳市",
  "Shenzhen": "深圳市",
  "Shihezi": "石河子市",
  "Shijiazhuang": "石家庄市",
  "Shijiazhuang Shi": "石家庄市",
  "Shiyan": "十堰市",
  "Shizuishan": "石嘴山市",
  "Shuangyashan": "双鸭山市",
  "Shuozhou": "朔州市",
  "Siping": "四平市",
  "Songyuan": "松原市",
  "SuQian": "宿迁市",
  "SuZhou": "宿州市",
  "Suihua": "绥化市",
  "Suining": "遂宁市",
  "Suizhou": "随州市",
  "Suzhou": "宿州市",
  "Suzhou Shi": "宿州市",
  "Tacheng": "塔城地区",
  "Tacheng Diqu": "塔城地区",
  "TaiZhou": "台州市",
  "Taiyuan": "太原市",
  "Taizhou": "台州市",
  "Tangshan": "唐山市",
  "Tangshan Shi": "唐山市",
  "Tianjin": "天津市",
  "Tianshui": "天水市",
  "Tieling": "铁岭市",
  "Tieling Shi": "铁岭市",
  "Tongchuan": "铜川市",
  "Tongchuanshi": "铜川市",
  "Tonghua": "通化市",
  "Tonghua Shi": "通化市",
  "Tongliao": "通辽市",
  "Tongren": "铜仁市",
  "Tongren Diqu": "铜仁市",
  "Wanning": "万宁市",
  "Weifang": "潍坊市",
  "Weihai": "威海市",
  "Weinan": "渭南市",
  "Wenchang": "文昌市",
  "Wenshan Zhuangzu Miaozu Zizhizhou": "文山壮族苗族自治州",
  "Wenzhou": "温州市",
  "WuXi": "无锡市",
  "Wuhai": "乌海市",
  "Wuhan": "武汉市",
  "Wuhu": "芜湖市",
  "Wuwei": "武威市",
  "Wuxi": "无锡市",
  "Wuzhong": "吴忠市",
  "Wuzhou": "梧州市",
  "Xiamen": "厦门市",
  "Xiangtan": "湘潭市",
  "Xiangxi Tujiazu Miaozu Zizhizhou": "湘西土家族苗族自治州",
  "Xiangyang": "襄阳市",
  "Xianning": "咸宁市",
  "Xianning Prefecture": "咸宁市",
  "Xiantao": "仙桃市",
  "Xianyang": "咸阳市",
  "Xiaogan": "孝感市",
  "Xingtai": "邢台市",
  "Xining": "西宁市",
  "Xinxiang": "新乡市",
  "Xinxiang Shi": "新乡市",
  "Xinxing": "新星市",
  "Xinyang": "信阳市",
  "Xinyu": "新余市",
  "Xinzhou": "忻州市",
  "XuZhou": "徐州市",
  "Xuchang": "许昌市",
  "Xuchang Shi": "许昌市",
  "YanCheng": "盐城市",
  "Yanbian Chaoxianzu Zizhizhou": "延边朝鲜族自治州",
  "Yancheng": "盐城市",
  "YangZhou": "扬州市",
  "Yangjiang": "阳江市",
  "Yangquan": "阳泉市",
  "Yangzhou": "扬州市",
  "Yantai": "烟台市",
  "Yibin": "宜宾市",
  "Yichang": "宜昌市",
  "Yichun": "宜春市",
  "Yinchuan": "银川市",
  "Yingkou": "营口市",
  "Yiyang": "益阳市",
  "Yongzhou": "永州市",
  "Yueyang": "岳阳市",
  "Yueyang Shi": "岳阳市",
  "Yulin": "榆林市",
  "Yulinshi": "榆林市",
  "Yuncheng": "运城市",
  "Yunfu": "云浮市",
  "Yushu Zangzu Zizhizhou": "玉树藏族自治州",
  "Yuxi": "玉溪市",
  "Zaozhuang": "枣庄市",
  "Zhangjiajie": "张家界市",
  "Zhangjiakou": "张家口市",
  "Zhangjiakou Shi": "张家口市",
  "Zhangye": "张掖市",
  "Zhangye Shi": "张掖市",
  "Zhangzhou": "漳州市",
  "Zhanjiang": "湛江市",
  "Zhaoqing": "肇庆市",
  "Zhaotong": "昭通市",
  "ZhenJiang": "镇江市",
  "Zhengzhou": "郑州市",
  "Zhenjiang": "镇江市",
  "Zhongshan": "中山市",
  "Zhongshan Prefecture": "中山市",
  "Zhongwei": "中卫市",
  "Zhoukou": "周口市",
  "Zhoushan": "舟山市",
  "Zhuhai": "珠海市",
  "Zhumadian": "驻马店市",
  "Zhumadian Shi": "驻马店市",
  "Zhuzhou": "株洲市",
  "Zhuzhou Shi": "株洲市",
  "Zibo": "淄博市",
  "Zigong": "自贡市",
  "Zunyi": "遵义市"
};
